version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    env_file:
    - docker.env
    networks:
    - postgres
    restart: always

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    env_file:
    - docker.env
    networks:
    - postgres

  frontend:
    container_name: frontend
    build: ./frontend/.
    image: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '3000:3000'

  backend:
    container_name: backend
    build: ./backend/.
    image: backend
    depends_on:
      - postgres
    restart: always
    ports:
      - '3001:3001'
      - '80:80'

networks:
  postgres:
    driver: bridge
