import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

/* We have a class called Post that has three properties: id, title, and content. 

The id property is a number that is automatically generated by the database. 

The title and content properties are strings */
@Entity()
class Post {
	@PrimaryGeneratedColumn()
	public id: number;

	@Column()
	public title: string;

	@Column()
	public content: string;
}

export default Post;
